name: 'Build Test'

on:
  push:
    branches:
      - main
      - develop

env:
  NODE_VERSION: 18

jobs:
  ci:
    name: 'Run CI'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Show Version
        run: |
          echo "$steps.package-version.outputs.current-version"
